name: 'ikvm-devops-images'

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
      
jobs:
  windows_server_2022:
    name: Windows Server 2022
    environment: alethic
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: "04ce8e2a-38ad-4252-b8ba-b1604a911b48"
        tenant-id: "fce092d1-b0b2-407f-a998-2fb77ebf4cc9"
        subscription-id: "0b41a26d-8ea0-4f1b-a652-ac81a0071ffb"
    - uses: andrew-fennell/create-env-json@v3
      id: create-env
      with:
        file-name: 'packer-vars.json'
        managed_image_resource_group_name: ikvm-devops-images
        managed_image_name: ikvm-devops-runner-windows-server-2022
        shared_image_gallery_resource_group: ikvm-devops-images
        shared_image_gallery_name: ikvmdevopsimages
        shared_image_gallery_image_name: ikvm-devops-runner-windows-server-2022
        image_version: '0.0.0'
        install_password: iPhCrae0PQHP8EiETN5dffugE1eY6qQB
        location: eastus2
    - name: Packer Build
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort -var-file ./packer-vars.json"
        target: "windows/windows-server-2022.json"
        working_directory: packer
