name: 'ikvm-github-images'

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
      
jobs:
  windows_2022:
    name: Windows 2022
    environment: alethic
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: "04ce8e2a-38ad-4252-b8ba-b1604a911b48"
        tenant-id: "fce092d1-b0b2-407f-a998-2fb77ebf4cc9"
        subscription-id: "0b41a26d-8ea0-4f1b-a652-ac81a0071ffb"
    - name: Packer Install
      run: sudo apt-get install -y packer
    - name: Packer Build
      run: |
        packer build -color=false -on-error=abort \
          -var "subscription_id=0b41a26d-8ea0-4f1b-a652-ac81a0071ffb" \
          -var "build_resource_group_name=ikvm-github-images-build" \
          -var "managed_image_resource_group_name=ikvm-github-images" \
          -var "managed_image_name=ikvm-github-runner-windows-2022" \
          -var "shared_image_gallery_resource_group=ikvm-github-images" \
          -var "shared_image_gallery_name=ikvmgithubimages" \
          -var "shared_image_gallery_image_name=ikvm-github-runner-windows-2022" \
          -var "shared_image_gallery_image_version=0.0.0" \
          -var "install_password=iPhCrae0PQHP8EiETN5dffugE1eY6qQB" \
          -var "location=eastus2" \
          windows/windows-2022.json
      