name: 'ikvm-github-images'

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
      
jobs:
  windows_2022:
    name: Windows 2022
    environment: alethic
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Calculate Version
      id: version
      run: echo "::set-output name=version::$(date '+%Y%m%d').0.${GITHUB_RUN_NUMBER}"
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZ_CLIENT_ID }}
        tenant-id: ${{ secrets.AZ_TENANT_ID }}
        subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
    - name: Use latest Packer
      uses: hashicorp-contrib/setup-packer@v1
    - name: Packer Build
      run: >
        packer build -color=false -on-error=cleanup
        -var "use_azure_cli_auth=true"
        -var "subscription_id=${{ secrets.AZ_SUBSCRIPTION_ID }}"
        -var "build_resource_group_name=${{ secrets.AZ_BUILD_RESOURCE_GROUP_NAME }}"
        -var "managed_image_resource_group_name=${{ secrets.AZ_IMAGE_RESOURCE_GROUP_NAME }}"
        -var "managed_image_name=ikvm-github-runner-windows-2022"
        -var "shared_image_gallery_resource_group=${{ secrets.AZ_IMAGE_RESOURCE_GROUP_NAME }}"
        -var "shared_image_gallery_name=${{ secrets.AZ_IMAGE_GALLARY_NAME }}"
        -var "shared_image_gallery_image_name=ikvm-github-runner-windows-2022"
        -var "shared_image_gallery_image_version=${{ steps.version.outputs.version }}"
        -var "install_password=iPhCrae0PQHP8EiETN5dffugE1eY6qQB"
        -var "location=${{ secrets.AZ_LOCATION }}"
        windows/windows-2022.json
      