name: 'ikvm-devops-images'

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

env:
  PKR_VAR_managed_image_resource_group_name: ikvm-devops-images
  PKR_VAR_shared_image_gallery_resource_group: ikvm-devops-images
  PKR_VAR_shared_image_gallery_name: ikvmdevopsimages
  PKR_VAR_install_password: iPhCrae0PQHP8EiETN5dffugE1eY6qQB
      
jobs:
  windows_server_2022:
    name: Windows Server 2022
    environment: default
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: "731ad181-4fc2-4493-aa07-dfae73961c14"
        client-secret: "H6x.il0dBlGro8M.-Zdl.ZF0T7dN45S.In"
        tenant-id: "fce092d1-b0b2-407f-a998-2fb77ebf4cc9"
        subscription-id: "0b41a26d-8ea0-4f1b-a652-ac81a0071ffb"
    - name: Validate Image
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: 'windows/windows-server-2022.json'
    - name: Build Image
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort"
        target: 'windows/windows-server-2022.json'
      env:
        PKR_VAR_location: eastus2
        PKR_VAR_managed_image_name: ikvm-devops-agent-windows-server-2022
        PKR_VAR_shared_image_gallery_image_name: ikvm-devops-agent-windows-server-2022
    